### ISSUE TITLE
Error during validation.

### ISSUE THREAD

**Issue by a-klos** [mikelzc1990/nsganetv2#13]
When I try to run python validation.py ... the following exception is thrown:

```
Traceback (most recent call last):
  File "/home/user/github/nsganetv2/validation.py", line 10, in <module>
    from codebase.run_manager import get_run_config
  File "/home/user/github/nsganetv2/codebase/run_manager/__init__.py", line 1, in <module>
    from codebase.data_providers.imagenet import *
  File "/home/user/github/nsganetv2/codebase/data_providers/imagenet.py", line 10, in <module>
    from ofa.utils.my_dataloader import MyRandomResizedCrop, MyDistributedSampler
ModuleNotFoundError: No module named 'ofa.utils.my_dataloader'; 'ofa.utils' is not a package
```

**Comment by a-klos** [comment]
I fixed it by installing the latest version of ofa:

pip install git+https://github.com/mit-han-lab/once-for-all@e9b0e07410e9d9f9e19b2dc0a5a5d66961336cb7

The release version 0.1 did **not** fix the issue.
