### ISSUE TITLE
ImportError: cannot import name 'str_to_pil_interp' from 'timm.data.transforms' 

### ISSUE THREAD

**Issue by yujialiang1997** [mikelzc1990/nsganetv2#14]
No matter how I run msunas.py or evaluator.py or train_cifar.py,There will always be such mistakes：
sudo+ssh://root@124.222.198.97:8002/root/anaconda3/bin/python3.7 -u /home/yujialiang/nsganetv2-master/train_cifar.py
Traceback (most recent call last):
  File "/home/yujialiang/nsganetv2-master/train_cifar.py", line 20, in <module>
    from evaluator import OFAEvaluator
  File "/home/yujialiang/nsganetv2-master/evaluator.py", line 9, in <module>
    from codebase.run_manager import get_run_config
  File "/home/yujialiang/nsganetv2-master/codebase/run_manager/__init__.py", line 5, in <module>
    from codebase.data_providers.dtd import *
  File "/home/yujialiang/nsganetv2-master/codebase/data_providers/dtd.py", line 5, in <module>
    from timm.data.transforms import str_to_pil_interp
ImportError: cannot import name 'str_to_pil_interp' from 'timm.data.transforms' (/root/anaconda3/lib/python3.7/site-packages/timm/data/transforms.py)

I think it may be that the version of timm does not correspond，but the timm version I did install was 0.1.30.
I don 't know where the problem is. Would you like to anwser this question? 
Thank you very much!

**Comment by yongyuan-chen** [comment]
pip install timm==0.5.4
